// <auto-generated />
using System;
using GestionStockCore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionStockCore.DAL.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Customer", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("reference");

                    b.Property<bool>("Deleted")
                        .HasColumnType("BIT")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("phone");

                    b.HasKey("Reference");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Reference = "LYKH0001",
                            Deleted = false,
                            Email = "lykhun@gmail.com",
                            FirstName = "Khun",
                            LastName = "Ly"
                        },
                        new
                        {
                            Reference = "LYPI0001",
                            Deleted = false,
                            Email = "piv.ly@bstorm.be",
                            FirstName = "Piv",
                            LastName = "Ly"
                        },
                        new
                        {
                            Reference = "PEMI0001",
                            Deleted = false,
                            Email = "michael.person@cognitic.be",
                            FirstName = "Mike",
                            LastName = "Person"
                        },
                        new
                        {
                            Reference = "MOTH0001",
                            Deleted = false,
                            Email = "tierry.morre@cognitic.be",
                            FirstName = "Thierry",
                            LastName = "Morre"
                        },
                        new
                        {
                            Reference = "COJU0001",
                            Deleted = false,
                            Email = "julien.coppin@bstorm.be",
                            FirstName = "Julien",
                            LastName = "Coppin"
                        },
                        new
                        {
                            Reference = "COJU0002",
                            Deleted = false,
                            Email = "julie@courtois.be",
                            FirstName = "Julie",
                            LastName = "Courtois"
                        },
                        new
                        {
                            Reference = "STAU0001",
                            Deleted = false,
                            Email = "aurelien.strimelle@bstorm.be",
                            FirstName = "Aurélien",
                            LastName = "Strimelle"
                        },
                        new
                        {
                            Reference = "OVFL0001",
                            Deleted = false,
                            Email = "flavian.ovyn@bstorm.be",
                            FirstName = "Flavian",
                            LastName = "Ovyn"
                        },
                        new
                        {
                            Reference = "LAST0001",
                            Deleted = false,
                            Email = "steve.laurent@bstorm.be",
                            FirstName = "Steve",
                            LastName = "Laurent"
                        },
                        new
                        {
                            Reference = "BALO0001",
                            Deleted = false,
                            Email = "loic.baudoux@bstorm.be",
                            FirstName = "Loïc",
                            LastName = "Baudoux"
                        },
                        new
                        {
                            Reference = "PEMI0002",
                            Deleted = false,
                            Email = "michel@pedro.be",
                            FirstName = "Michel",
                            LastName = "Pedro"
                        },
                        new
                        {
                            Reference = "COJU0003",
                            Deleted = false,
                            Email = "jules@constant.be",
                            FirstName = "Jules",
                            LastName = "Constant"
                        });
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Order", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(10)
                        .HasColumnType("CHAR(10)")
                        .HasColumnName("reference");

                    b.Property<string>("CustomerRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("customerRef");

                    b.Property<int>("Status")
                        .HasColumnType("INT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updateDate");

                    b.HasKey("Reference");

                    b.HasIndex("CustomerRef");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Reference = "2201310001",
                            CustomerRef = "MOTH0001",
                            Status = 0,
                            UpdateDate = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Reference = "2201310002",
                            CustomerRef = "PEMI0001",
                            Status = 3,
                            UpdateDate = new DateTime(2022, 1, 31, 0, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Reference = "2201310003",
                            CustomerRef = "COJU0001",
                            Status = 2,
                            UpdateDate = new DateTime(2022, 1, 31, 4, 2, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Reference = "2201310004",
                            CustomerRef = "COJU0001",
                            Status = 1,
                            UpdateDate = new DateTime(2022, 1, 31, 5, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("CHAR(10)")
                        .HasColumnName("orderRef");

                    b.Property<string>("ProductRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("productRef");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("MONEY")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id");

                    b.HasIndex("OrderRef");

                    b.HasIndex("ProductRef");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderRef = "2201310001",
                            ProductRef = "COCA0001",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            OrderRef = "2201310002",
                            ProductRef = "JUPI0001",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            OrderRef = "2201310003",
                            ProductRef = "COCA0002",
                            Quantity = 100,
                            UnitPrice = 19.92m
                        },
                        new
                        {
                            Id = 4,
                            OrderRef = "2201310004",
                            ProductRef = "FANT0002",
                            Quantity = 25,
                            UnitPrice = 16.24m
                        },
                        new
                        {
                            Id = 5,
                            OrderRef = "2201310004",
                            ProductRef = "COCA0001",
                            Quantity = 20,
                            UnitPrice = 16.24m
                        });
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Product", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("reference");

                    b.Property<bool>("Deleted")
                        .HasColumnType("BIT")
                        .HasColumnName("deleted");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("INT")
                        .HasColumnName("stock");

                    b.HasKey("Reference");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Reference = "COCA0001",
                            Deleted = false,
                            Description = "CAN. 24X33cl",
                            Name = "Coca Cola 33cl",
                            Price = 16.8m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "COCA0002",
                            Deleted = false,
                            Description = "CAN. 24X50cl",
                            Name = "Coca Cola 50cl",
                            Price = 19.92m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "COCA0003",
                            Deleted = false,
                            Description = "BOUT. 6X1l",
                            Name = "Coca Cola 1l",
                            Price = 10.92m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "FANT0001",
                            Deleted = false,
                            Description = "CAN. 24X33cl",
                            Name = "Fanta Orange 33cl",
                            Price = 16.8m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "FANT0002",
                            Deleted = false,
                            Description = "CAN. 24X33cl",
                            Name = "Fanta Citron 33cl",
                            Price = 16.8m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "FANT0003",
                            Deleted = false,
                            Description = "CAN. 24X50cl",
                            Name = "Fanta Orange 50cl",
                            Price = 16.8m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "FANT0004",
                            Deleted = false,
                            Description = "CAN. 24X50cl",
                            Name = "Fanta Citron 50cl",
                            Price = 19.92m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "JUPI0001",
                            Deleted = false,
                            Description = "CAN. 24X33cl",
                            Name = "Jupiler 33cl",
                            Price = 29.04m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "JUPI0002",
                            Deleted = false,
                            Description = "CAN. 24X50cl",
                            Name = "Jupiler 50cl",
                            Price = 35.52m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "CARL0001",
                            Deleted = false,
                            Description = "CAN. 24X33cl",
                            Name = "Carlsberg 33cl",
                            Price = 32.4m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "CHIM0001",
                            Deleted = false,
                            Description = "BOUT. 24X33cl",
                            Name = "Chimay Bleue 33cl",
                            Price = 45.6m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "CHIM0002",
                            Deleted = false,
                            Description = "BOUT. 24X33cl",
                            Name = "Chimay Rouge 33cl",
                            Price = 45.6m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "CHIM0003",
                            Deleted = false,
                            Description = "BOUT. 24X33cl",
                            Name = "Chimay Blanche 33cl",
                            Price = 30.24m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "NALU0001",
                            Deleted = false,
                            Description = "CAN. 24X25cl",
                            Name = "Nalu Vert 25cl",
                            Price = 16.8m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "EVIA0001",
                            Deleted = false,
                            Description = "BOUT. 8X1l",
                            Name = "Evian 1l",
                            Price = 8.96m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "EVIA0002",
                            Deleted = false,
                            Description = "BOUT. 24X50cl",
                            Name = "Evian 50cl",
                            Price = 5.6m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "VITT0001",
                            Deleted = false,
                            Description = "BOUT. 8X1l",
                            Name = "Vittel 1l",
                            Price = 8.72m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "VITT0002",
                            Deleted = false,
                            Description = "BOUT. 24X50cl",
                            Name = "Vittel 50cl",
                            Price = 5.44m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "OASI0001",
                            Deleted = false,
                            Description = "BOUT. 6X2l",
                            Name = "Oasis Orange 2l",
                            Price = 13.44m,
                            Stock = 1000
                        },
                        new
                        {
                            Reference = "OASI0002",
                            Deleted = false,
                            Description = "BOUT. 6X2l",
                            Name = "Oasis Tropical 2l",
                            Price = 13.44m,
                            Stock = 1000
                        });
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Order", b =>
                {
                    b.HasOne("GestionStockCore.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.OrderLine", b =>
                {
                    b.HasOne("GestionStockCore.DAL.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionStockCore.DAL.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("GestionStockCore.DAL.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
